"""init table & add demo data

Revision ID: cada1a3b13bd
Revises: 
Create Date: 2023-07-05 16:51:19.810778

"""
from json import loads
from pathlib import Path

import sqlalchemy as sa
from alembic import op

## path (for demo data)
server_folder = Path(".").parent


# revision identifiers, used by Alembic.
revision = "cada1a3b13bd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user = op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # add demo data
    with open(server_folder.joinpath("migrations/demo-data/users.json")) as f:
        user_data = loads(f.read())
    op.bulk_insert(user, user_data)

    following = op.create_table(
        "following",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("follower_id", sa.Integer(), nullable=False),
        sa.Column("followee_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["followee_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # add demo data
    with open(
        server_folder.joinpath("migrations/demo-data/followings.json")
    ) as f:
        followings_data = loads(f.read())
    op.bulk_insert(following, followings_data)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("following")
    op.drop_table("user")
    # ### end Alembic commands ###
